Change the build system to enable building with Qt 6
This was built with:
-DQT_MAJOR_VERSION=6 \
-DEXCLUDE_DEPRECATED_BEFORE_AND_AT=5.90.0 \
-DKF_DISABLE_DEPRECATED_BEFORE_AND_AT=0x055a00

Remove operator<<(QDebug, Attica::Provider const&); in Qt6 QMetaTypes that
have such an operator now have a requirement to make it visible to the linker,
otherwise the build fails:
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld:
CMakeFiles/providertest.dir/providertest.cpp.o: in function
`QtPrivate::QDebugStreamOperatorForType<Attica::Provider, true>::debugStream(QtPrivate::QMetaTypeInterface const*, QDebug&, void const*)':
/usr/include/qt6/QtCore/qmetatype.h:2216: undefined reference to `operator<<(QDebug, Attica::Provider const&)'

Since it's not used anywhere, remove it altogether as suggested by Volker.

All unit tests still pass.