-require cmake 2.8.11
With earlier versions it does not build for me:

[100%] Building CXX object lib/tests/CMakeFiles/persontest.dir/persontest.cpp.o
In file included from /opt/qt5/include/QtCore/qnamespace.h:45:0,
                 from /opt/qt5/include/QtCore/qobjectdefs.h:45,
                 from /opt/qt5/include/QtCore/qobject.h:48,
                 from /opt/qt5/include/QtCore/qabstractanimation.h:45,
                 from /opt/qt5/include/QtCore/QtCore:4,
                 from /opt/qt5/include/QtTest/QtTestDepends:2,
                 from /opt/qt5/include/QtTest/QtTest:3,
                 from /home/alex/src/kde-git/attica/lib/tests/persontest.cpp:24:
/opt/qt5/include/QtCore/qglobal.h:975:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. "
                                                       "Compile your code with -fPIC or -fPIE."

This must be due to the features related to target properties added in cmake 2.8.11 by Stephen.

Alex